### ISSUE TITLE
Auto Analysis dosen´t works

### ISSUE THREAD

**Issue by Fortesque0** [ArduPilot/MissionPlanner#1595]
#### Issue details
I use Auto Analysis feature but returns an error

#### Version
MP 1.348.3 Beta
#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
Trade Heli

#### Hardware type
pixhawk

#### Logs
![error](https://user-images.githubusercontent.com/17238988/28140714-c22fe5e2-6759-11e7-9611-06722a1ae866.PNG)

**Comment by smiltee** [comment]
Can you provide an input file?

**Comment by Fortesque0** [comment]
Hello, 
Yes, I will upload some files soon.
Thanks

**Comment by Fortesque0** [comment]
Sorry for delay. I am on holidays. 
[Auto_log_bad.zip](https://github.com/ArduPilot/MissionPlanner/files/1184816/Auto_log_bad.zip)

**Comment by meee1** [comment]
for some reason MOT_PWM_MIN doesn't exist in that log. and is causing it to fail

**Comment by meee1** [comment]
Traceback (most recent call last):
  File "runner.py", line 6, in <module>
  File "LogAnalyzer.pyc", line 246, in main
  File "LogAnalyzer.pyc", line 91, in run
  File "C:\ProgramData\Mission Planner\LogAnalyzer\/tests\TestMotorBalance.py", line 44, in run
    min_throttle = logdata.parameters["MOT_PWM_MIN"] / (logdata.parameters["MOT_PWM_MAX"]-logdata.parameters["RC3_MIN"])/1000.0
KeyError: 'MOT_PWM_MIN'
