### ISSUE TITLE
Current release on MP failed to fetch log list.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/MissionPlanner#2252]
#### Issue details
Downloading log list produces:
Getting list of log files...
Error:System.TimeoutException: Timeout on read - GetLogEntry
   at MissionPlanner.MAVLinkInterface.GetLogEntry(UInt16 startno, UInt16 endno)
   at MissionPlanner.MAVLinkInterface.GetLogList()
   at MissionPlanner.Log.LogDownloadMavLink.<LoadLogList>b__12_0()

#### Version
1.3.68

#### Platform
Copter v4-dev

#### Hardware type
Cube

#### Logs
Getting list of log files...
Error:System.TimeoutException: Timeout on read - GetLogEntry
   at MissionPlanner.MAVLinkInterface.GetLogEntry(UInt16 startno, UInt16 endno)
   at MissionPlanner.MAVLinkInterface.GetLogList()
   at MissionPlanner.Log.LogDownloadMavLink.<LoadLogList>b__12_0()

**Comment by AndKe** [comment]
current master does it marginally better: 

Getting list of log files...
Found 500 log files, note: item sizes are just an estimate.
Downloading log files to: C:\Program Files\Mission Planner\logs
Fetching log file 12.09.2015 08:35:32 ...
Creating KML for 2015-09-12 08-33-03.log
Fetching log file 12.09.2015 08:48:56 ...
Error in log Timeout on read - GetLog


at this point, it is not clear whatever it stopped, or the timeout is a warning, and it will be resumed.
in any case, the log fetching is not reliable. (directly connected over serial port)
Also: stopping/reducing SR* telemetry rates would help the performance.
