### ISSUE TITLE
Exception on any FENCE download request

### ISSUE THREAD

**Issue by Hwurzburg** [ArduPilot/MissionPlanner#2393]
This happens anytime a download of the fences is requested, whether fence points are loaded or not
ERROR MissionPlanner.ArduPilot.mav_mission - System.TimeoutException: Timeout on read - getWPCount
   at MissionPlanner.MAVLinkInterface.<getWPCountAsync>d__194.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MissionPlanner.ArduPilot.mav_mission.<download>d__1.MoveNext()
#### Platform
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Sub

Beta and new May release versions tested

**Comment by Hwurzburg** [comment]
resolved
