### ISSUE TITLE
ERROR GDAL.GDAL - System.Exception: Invalid coords

### ISSUE THREAD

**Issue by itayguy** [ArduPilot/MissionPlanner#3330]
#### Issue details
console windows error

#### Version
1.3.81 beta

#### Logs
ERROR GDAL.GDAL - System.Exception: Invalid coords
   at GDAL.GDAL.LoadImageInfo(String file) in D:\a\MissionPlanner\MissionPlanner\ExtLibs\GDAL\GDAL.cs:line 123
   at GDAL.GDAL.ScanDirectory(String path) in D:\a\MissionPlanner\MissionPlanner\ExtLibs\GDAL\GDAL.cs:line 102
ERROR 4: `C:\Users\user\Downloads\2024-03-13 21-36-16.tlog' not recognized as a supported file format.
ERROR GDAL.GDAL - System.ApplicationException: `C:\Users\user\Downloads\2024-03-13 21-36-16.tlog' not recognized as a supported file format.
   at OSGeo.GDAL.Gdal.Open(String utf8_path, Access eAccess)
   at GDAL.GDAL.LoadImageInfo(String file) in D:\a\MissionPlanner\MissionPlanner\ExtLibs\GDAL\GDAL.cs:line 123
   at GDAL.GDAL.ScanDirectory(String path) in D:\a\MissionPlanner\MissionPlanner\ExtLibs\GDAL\GDAL.cs:line 102
ERROR 4: `C:\Users\user\Downloads\2024-04-04 17-17-54 (1).rlog' not recognized as a supported file format.
ERROR GDAL.GDAL - System.ApplicationException: `C:\Users\user\Downloads\2024-04-04 17-17-54 (1).rlog' not recognized as a supported file format.
   at OSGeo.GDAL.Gdal.Open(String utf8_path, Access eAccess)
   at GDAL.GDAL.LoadImageInfo(String file) in D:\a\MissionPlanner\MissionPlanner\ExtLibs\GDAL\GDAL.cs:line 123
   at GDAL.GDAL.ScanDirectory(String path) in D:\a\MissionPlanner\MissionPlanner\ExtLibs\GDAL\GDAL.cs:line 102

**Comment by meee1** [comment]
This is dependant on your setup. But I agree a tlog is not a valid gdal source. So not sure why you set gdal to attempt to load it.
